version: "3"
networks:
  api_server_default:
    external: true
services:
  linksearcherapp:
    volumes:
      - .:/usr/src/app
    networks:
      - api_server_default
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_NAME: dev
    ports:
      - 7001:7001
      - 3000:3000
      - 5858:5858
    command: npm start